name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - run: go version
      - name: Run build
        run: make clean build
      - name: Run test
        run: make test.race
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: Docker build base
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: false
      #     build-args: |
      #       MAKE_TARGET=test build
      - name: Set output
        id: vars
        run: echo ::set-output name=sha::${GITHUB_SHA}
      - name: Docker publish
        uses: daspawnw/docker-multi-build-push-action@master
        with:
          docker-tag: "${{ steps.vars.outputs.sha }}"
          ghcr-enabled: "true"
          ghcr-token: "${{ secrets.GITHUB_TOKEN }}"
          ecr-enabled: "false"
